### PR TITLE
Add jsmain to package.json

### PR DESCRIPTION
**Pull request by svozza**
As mentioned in https://github.com/CascadeEnergy/dynamoDb-marshaler/issues/16, I've added the `jsnext:main` to `package.json`. I wasn't sure if I should commit the transpiled version of the code so if you want me to removed it just let me know.

### CODE REVIEW

**Comment by nackjicholson** [comment]
@svozza Thanks for the commit. I'm not sure if you should commit the transpiled code either. Probably not.

If you look at another module dispatch-fn which is super simple. Recently I rewrote it and ripped out all of the babel and gulp overhead. I'm thinking of doing that same thing with this module.

What does the jsnext:main key do out of curiosity? Just help people find the untranspiled source? Can people target the es6 directly somehow? I don't think it will be necessary if we just revert this back to plain 0.10 es5.

**Comment by svozza** [comment]
Yep, `jsnext` allows tools like Rollup identify ES6 modules to be included in a build. If `dispatch-recursive` is rewritten in ES5 then there's no need for this pull request although I still think using the `lodash.undefined` dependency rather than all of `lodash` would be a good idea. I'll happily change this PR to convert the module to ES5 if you want.

**Comment by notxt** [comment]
@svozza I would be overjoyed if you wanted to put in a pr converting to es5! I could review and merge later this week for sure. In the meantime, I'm going to close this one 'cause @jinsyaoommen is nagging me 😓

**Comment by svozza** [comment]
Done!

**Pull request closed without merging**
